# Database Configuration
database:
  path: "customer_churn.db"
  table_name: "customers"

# Data Configuration
data:
  raw_data_path: "WA_Fn-UseC_-Telco-Customer-Churn.csv"
  test_size: 0.2
  random_state: 42

# Feature Configuration
features:
  target_column: "Churn"
  customer_id_column: "customerID"
  
  numeric_features:
    - "tenure"
    - "MonthlyCharges"
    - "TotalCharges"
  
  categorical_features:
    - "gender"
    - "SeniorCitizen"
    - "Partner"
    - "Dependents"
    - "PhoneService"
    - "MultipleLines"
    - "InternetService"
    - "OnlineSecurity"
    - "OnlineBackup"
    - "DeviceProtection"
    - "TechSupport"
    - "StreamingTV"
    - "StreamingMovies"
    - "Contract"
    - "PaperlessBilling"
    - "PaymentMethod"
  
  engineered_features:
    - "MonthlyToTotalRatio"
    - "NumAdditionalServices"
    - "HasInternetService"

# Model Configuration
models:
  output_dir: "models/"
  
  logistic_regression:
    penalty: "l2"
    C: 1.0
    max_iter: 1000
  
  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    class_weight: "balanced"
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    subsample: 1.0

# Training Configuration
training:
  use_smote: true
  cv_folds: 5
  scoring_metric: "f1"
  n_iter_search: 20
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true